name: Test Project
on: [push, workflow_dispatch]   # here we added mutiple run options.
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3  # Here node js comes pre installed with Ubuntu, but for testing we done.
        with:
          node-version: 18
      - name: Install dependecies
        run: npm ci
      - name: Run tests
        run: npm test
  deploy:
    needs: test  # here we mentioned needs means this job should start after test complated.
    runs-on: ubuntu-latest
    steps:
    - name: Get code
      uses: actions/checkout@v3
    - name: Install NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Build Project
      run: npm run build
    - name: Deploy 
      run: echo "Deploying ..."